name: cmods
on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  install-qt:
    runs-on: macos-latest
    steps:
       - name: Install Qt
         uses: jurplel/install-qt-action@v3
         with:
          aqtversion: '==3.1.*'
          py7zrversion: '>=0.20.2'
          version: '6.4.1'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          cache: true

       - uses: actions/checkout@v3
       - name: Configure CMake
         # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
         # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
         run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=/Users/runner/work/CMoDS/Qt/6.4.1/macos/lib/cmake/Qt6

       - name: Build
         # Build your program with the given configuration
         run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

       - name: Test
         working-directory: ${{github.workspace}}/build
         # Execute tests defined by the CMake configuration.
         # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
         run: ./tests/tests.app/Contents/MacOS/tests && sh ../CMoDS/tests/run_coverage.sh && cat ../CMoDS/coverage/html/index.html
       
          
  generate-badge:
    runs-on: macos-latest
    steps:
      - name: Create Qt Badge
        uses:  Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ae8c2bc1a7c8ee405589fe1b957d532b
          filename: cmods.json
          label: Qt
          message: 6.4.1
          color: brightgreen
      - name: Create CMake Badge
        uses:  Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a6f4b009d37f07b7b60a0c89c53cb0f7
          filename: cmakev.json
          label: CMake
          message: 3.16
          color: blue
